### ISSUE TITLE
The data don't matching

### ISSUE THREAD

**Issue by dcasonic** [moneymanagerex/general-reports#28]
I liked the report: Expense and Revenue report by Year. But this report don't matching with the default program report (receive vs expenses - current year).
Please, look the attached files to check.
Maybe, the problem is me. But if so.. please help me.
Thank you.
![report_correct](https://cloud.githubusercontent.com/assets/7902315/7070531/fa470426-deb5-11e4-9a0f-11567eb251eb.jpg)
![report_issue](https://cloud.githubusercontent.com/assets/7902315/7070530/fa444de4-deb5-11e4-84de-78372d738855.jpg)

**Comment by loki36** [comment]
I will check i think there is an error in my query.

**Comment by loki36** [comment]
ok I found what there is the error :  
I don't understand the status of transaction but i need to ad in query this filter : where status <>'V'

**Comment by loki36** [comment]
should be ok, can you confirm

**Comment by dcasonic** [comment]
Yes. Confirmed. It's all ok now.
Thank you very much.
