### ISSUE TITLE
Accounts balance for any date

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/general-reports#42]
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6952

**Comment by vomikan** [comment]
@aprobinda could you create this report?

**Comment by aprobinda** [comment]
`select a.ACCOUNTNAME, 
    (
    select a.INITIALBAL + total(t.TRANSAMOUNT)
      from
	(select ACCOUNTID, STATUS, 
		(case when TRANSCODE = 'Deposit' then TRANSAMOUNT else -TRANSAMOUNT end) as TRANSAMOUNT 
,TRANSDATE
	from CHECKINGACCOUNT_V1
        union all
	select TOACCOUNTID, STATUS, TOTRANSAMOUNT
,TRANSDATE
          from CHECKINGACCOUNT_V1
          where TRANSCODE = 'Transfer'
	) as t
 where  
t.ACCOUNTID = a.ACCOUNTID 
and t.TRANSDATE <= '2017-02-25'
       and t.STATUS <> 'V'
   ) as Balance
from ACCOUNTLIST_V1 as a
where 
a.STATUS = 'Open'
group by a.ACCOUNTNAME
order by a.ACCOUNTNAME asc;`

**Comment by vomikan** [comment]
My SQL script is:
~~~~~~
with b as  (
	    select ACCOUNTID, STATUS
            , (case when TRANSCODE = 'Deposit' then TRANSAMOUNT else -TRANSAMOUNT end) as TRANSAMOUNT
            ,TRANSDATE 
            from CHECKINGACCOUNT_V1 
            union all 
            select TOACCOUNTID, STATUS, TOTRANSAMOUNT ,TRANSDATE 
            from CHECKINGACCOUNT_V1 
            where TRANSCODE = 'Transfer' 
   ) 
select a.ACCOUNTNAME, 
total(TRANSAMOUNT) + a.INITIALBAL as Balance 
from ACCOUNTLIST_V1 as a, b
where a.STATUS = 'Open' 
    and b.ACCOUNTID = a.ACCOUNTID 
    and b.STATUS <> 'V' 
    and b.TRANSDATE <= '2017-02-25' 
group by a.ACCOUNTNAME order by a.ACCOUNTNAME asc;
~~~~~~

**Comment by vomikan** [comment]
There is already present the report 'Account Summary' in mmex v 1.3.0
![screenshot 79](https://cloud.githubusercontent.com/assets/6836805/23647273/1cf4a67c-0326-11e7-8bf9-705e9f332e8b.jpg)
Seems it would be nice option to add a date option.

**Comment by vomikan** [comment]
Only for mmex >= 1.4.0 
[Account summary.zip](https://github.com/moneymanagerex/general-reports/files/833836/Account.summary.zip)

Use [nightly biild](https://ci.appveyor.com/project/guanlisheng/moneymanagerex) for tests

**Comment by vomikan** [comment]
![screenshot 97](https://cloud.githubusercontent.com/assets/6836805/23901749/a03996c4-08cf-11e7-95b5-e773a10cb876.jpg)

**Comment by vomikan** [comment]
@petubl 
Possible SQL for new DB structure:
```
with t as (select ACCOUNTID, STATUS, TRANSDATE,
            (case when TRANSCODE = 'Deposit' then TRANSAMOUNT else -TRANSAMOUNT end) as TRANSAMOUNT
        from CHECKINGACCOUNT
        where STATUS <>'V'
        union all
        select TOACCOUNTID, STATUS, TRANSDATE, TOTRANSAMOUNT 
        from CHECKINGACCOUNT
        where TRANSCODE = 'Transfer' and STATUS NOT LIKE 'V_') -- TODO: there are XX statuses available as well
, c as (select c.CURRENCYID, c.PFX_SYMBOL, c.SFX_SYMBOL , 
        max(h.CURRDATE) Date, h.CURRVALUE BASECONVRATE
        from CURRENCYFORMATS c
        left join CURRENCYHISTORY h on c.CURRENCYID=h.CURRENCYID
        where  h.CURRDATE<='&single_date'
        group by h.CURRENCYID
         union all
         select c.CURRENCYID, c.PFX_SYMBOL, c.SFX_SYMBOL , 
          '&single_date' , 1 
          from CURRENCYFORMATS c
          where c.CURRENCYID = (select INFOVALUE  from INFOTABLE where INFONAME='BASECURRENCYID'))
select a.ACCOUNTNAME, c.PFX_SYMBOL, c.SFX_SYMBOL,
 c.BASECONVRATE,
    total(t.TRANSAMOUNT) + a.INITIALBAL as Balance 
from ACCOUNTLIST as a, t, c
where a.ACCOUNTTYPE  not in ('Investment') 
and c.CURRENCYID = a.CURRENCYID
and a.STATUS = 'Open'
and a.ACCOUNTID=t.ACCOUNTID
and t.TRANSDATE <= '&single_date'
group by a.ACCOUNTNAME
order by a.ACCOUNTNAME asc;
```

**Comment by petubl** [comment]
Thank you very much @vomikan the sql code works now - i still get many decimal points on the 1st, 3rd, 5th, 7th etc lines on the report.

Any idea why this happens?

**Comment by vomikan** [comment]
@petubl I've just updated SQL code, please, update

**Comment by vomikan** [comment]
Most important changes:
- STATUS NOT LIKE '%V'  -- now transfer transaction has XX (2 bytes) status code.
- from CURRENCYHISTORY  -- now there is no BASECONVRATE value in CURRENCYFORMATS table.

**Comment by petubl** [comment]
Works great! Thanks

**Comment by vomikan** [comment]
I've created wet (draft) report with other graph generator. 
[Account.summary_10.zip](https://github.com/moneymanagerex/general-reports/files/2799120/Account.summary_10.zip)

It more complicated but looks better. But needed a lot of fixes.

![image](https://user-images.githubusercontent.com/6836805/51788943-8878b800-2194-11e9-804f-65715ab0af10.png)

**Comment by petubl** [comment]
The new graph looks very good! I prefer the multicolored list from the original report.

Thanks for your time in doing this!

**Comment by petubl** [comment]
@vomikan 
I spent some time playing around with the new report and have the following to report:

In the chart, the largest four accounts a represented by a different colour. However, the remaining accounts are displayed in the chart using the same colour as the one used in the case of the fourth one. So accounts 4, 5, 6, 7 etc are the same colour. 

In the table of the previous version of the report, you used a different colour for each total on the column on the right, labelled "Base Currency". I think it made the report more pleasing to the eye, but is not included in the new version. Do you think it can be brought back?

Thank you once again for your time in looking into this.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountBalances
