### ISSUE TITLE
Subtotals

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/general-reports#47]
https://forum.moneymanagerex.org/viewtopic.php?f=16&t=7484

**Comment by Sethadon** [comment]
**PROBLEM:** I am also not able to **subtotal** a column in one of my reports.

Here are some details:

**SQL:**
`SELECT chk.TRANSCODE, p.PAYEENAME, s.SUBCATEGNAME, chk.TOTRANSAMOUNT, chk.TRANSDATE, chk.NOTES
FROM CHECKINGACCOUNT_V1 chk, PAYEE_V1 p, CATEGORY_V1 ctg, SUBCATEGORY_V1 s
WHERE chk.PAYEEID = p.PAYEEID
AND chk.SUBCATEGID = s.SUBCATEGID
AND p.PAYEENAME LIKE '%some-payee-name%'
AND ctg.CATEGNAME LIKE '%some-category-name%'
AND chk.TRANSDATE BETWEEN 'start-date' AND 'end-date'
ORDER BY chk.TRANSDATE DESC;`

**XML:** [https://pastebin.com/raw/usdV3PV7](url)

**OUTPUT:** [https://ibb.co/3h1k6r0](url)
