### ISSUE TITLE
New Category report

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/general-reports#48]
Regarding this issue I've created GRM adapted report
https://github.com/moneymanagerex/moneymanagerex/issues/1689

![image](https://user-images.githubusercontent.com/6836805/41192171-c2822de4-6c02-11e8-95ca-217471f54fec.png)

[Categories_v4.zip](https://github.com/moneymanagerex/general-reports/files/2086988/Categories_v4.zip)

**Comment by slodki** [comment]
My original SQL from moneymanagerex/moneymanagerex#1689 should correctly report all amounts in base currency using historical rates (or 1:1 if not defined):

```sql
select
  CATEGNAME || coalesce(':' || SUBCATEGNAME, '') as ID,
  sum(TRANSAMOUNT) as amount
from (
  select
    coalesce(s.CATEGID, c.CATEGID) as CATEGID,
    coalesce(s.SUBCATEGID, c.SUBCATEGID) as SUBCATEGID,
    coalesce(CURRVALUE,1)*coalesce(SPLITTRANSAMOUNT,TRANSAMOUNT)*(case TRANSCODE when 'Withdrawal' then -1 else 1 end) as TRANSAMOUNT
  from CHECKINGACCOUNT c
    left join SPLITTRANSACTIONS s on s.TRANSID = c.TRANSID
    left join ACCOUNTLIST a on a.ACCOUNTID = c.ACCOUNTID
    left join CURRENCYHISTORY hist on (hist.CURRENCYID = a.CURRENCYID AND CURRDATE = (
      select max(h2.CURRDATE)
      from CURRENCYHISTORY h2
      where h2.CURRDATE<=TRANSDATE
    ))
  where TOACCOUNTID <> 32702 and TRANSCODE <> 'Transfer'
) as trans
  left join CATEGORY cat on cat.CATEGID = trans.CATEGID
  left join SUBCATEGORY subcat on subcat.SUBCATEGID = trans.SUBCATEGID  
group by ID
having amount < 0 -- <0 == Withdrawal, >0 == Deposit
;
```

**Comment by lexa2** [comment]
@slodki, thanks for your example query. In attachment you may find an updated Categories_v4 report with SQL query utilizing currency history in a similar way you did in your report. I had also done some minor changes to template (replaced toLocaleString with toFixed(2) at relevant places) 

[2018-07-19-#01-Categories_v4.zip](https://github.com/moneymanagerex/general-reports/files/2210261/2018-07-19-.01-Categories_v4.zip)

**Comment by vomikan** [comment]
This sql would work fine if currency exchange rates has been set correctly for all transaction date range.
If exchange rate is missing for some date in the past - it became 1.

**Comment by slodki** [comment]
This
```sql
select max(h2.CURRDATE)
from CURRENCYHISTORY h2
where h2.CURRDATE<=TRANSDATE
```
will:
1. select currency rate for given date if found
2. last known rate before given date
3. rate=1 if there are no historical rates till given date with `coalesce(CURRVALUE,1)`

**Comment by vomikan** [comment]
[Categories_v5.zip](https://github.com/moneymanagerex/general-reports/files/2799960/Categories_v5.zip)

**Comment by vomikan** [comment]
```//var color = d3.scaleSequential(d3.interpolateRainbow);
var color = d3.scaleOrdinal()
    .range(["#9E0142","#B3E2CD", "#FDCDAC", "#CBD5E8", "#F4CAE4", "#E6F5C9", "#FFF2AE", "#F1E2CC", "#CCCCCC"]);```
