### ISSUE TITLE
pacman repo appears to have out of date version

### ISSUE THREAD

**Issue by Castratikron** [moneymanagerex/general-reports#66]
It looks like the pacman repo still has version 1.3.3-3, while the website shows 1.3.5 as the stable version
![image](https://user-images.githubusercontent.com/26463709/96325677-b3a1db80-0ff7-11eb-9e8d-b1f731614bf1.png)
![image](https://user-images.githubusercontent.com/26463709/96325680-bf8d9d80-0ff7-11eb-916f-3b9c224f7512.png)

**Comment by vomikan** [comment]
Please recreate the issue there:
https://github.com/moneymanagerex/moneymanagerex/issues
Please specify the version of Linux.
