### ISSUE TITLE
Full financial year transaction and summary report

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/general-reports#73]
Just switched to a Mac having always used Windows and Microsoft Money to manage finances.

At the end of my financial year I always printed a transaction report (list of all income and expenses transactions) grouped by category, with totals for each category and grand totals at the end.

Is there a similar report for MMEX please, I don't see one like it displayed on the 'Reports' web page at GitHub

https://forum.moneymanagerex.org/viewtopic.php?f=16&t=10341

**Comment by worgretdons** [comment]
Just what I would like too.  Any progress yet?
