### ISSUE TITLE
Add installation instructions to readme doc

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/general-reports#81]
Please add installation instructions to readme doc that describe how you install these reports on a MMX Desktop.

**Comment by vomikan** [comment]
This information is available on the help page of the application.

![image](https://user-images.githubusercontent.com/6836805/212655071-eff788ab-e6d3-43b4-a58f-e9da3599c304.png)

**Comment by luisdev** [comment]
That's great. But the first place I looked was in the readme file and there was nothing there. And I was stuck wondering where to figure it out. So I still think the readme file needs SOME kind of installation instructions. That's what readme files are for...
